import os
import asyncio
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from jinja2 import Template
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Environment variables
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_EMAIL = os.getenv("FROM_EMAIL", SMTP_USER)

EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; color: #333; max-width: 700px; margin: auto;">
  <div style="background:#1a1a2e; padding: 24px; border-radius: 8px 8px 0 0;">
    <h1 style="color:#e94560; margin:0;">🎯 Interview Intelligence Report</h1>
    <p style="color:#ccc;">Session: {{ session_id }}</p>
  </div>

  <div style="padding: 24px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px;">
    <h2>Hello {{ candidate_name }},</h2>
    <p>Your interview analysis is ready. Here's your performance summary:</p>

    <table style="width:100%; border-collapse:collapse; margin: 16px 0;">
      <tr style="background:#f4f4f4;">
        <th style="padding:10px; text-align:left; border:1px solid #ddd;">Overall Score</th>
        <td style="padding:10px; border:1px solid #ddd; font-size:24px; font-weight:bold; color:#e94560;">
          {{ overall_score }}/100
        </td>
      </tr>
    </table>

    <h3>📊 Dimension Scores</h3>
    <table style="width:100%; border-collapse:collapse;">
      {% for key, val in scores.items() %}
      <tr>
        <td style="padding:8px; border:1px solid #eee; text-transform:capitalize;">
          {{ key.replace('_', ' ') }}
        </td>
        <td style="padding:8px; border:1px solid #eee; font-weight:bold;">
          {{ val }}/10
        </td>
      </tr>
      {% endfor %}
    </table>

    <h3>✅ Strengths</h3>
    <ul>
      {% for s in strengths %}
      <li>{{ s }}</li>
      {% endfor %}
    </ul>

    <h3>⚠️ Areas for Improvement</h3>
    <ul>
      {% for w in weaknesses %}
      <li>{{ w }}</li>
      {% endfor %}
    </ul>

    <h3>💡 Tips</h3>
    <ul>
      {% for t in tips %}
      <li>{{ t }}</li>
      {% endfor %}
    </ul>

    <p style="margin-top:24px; color:#777; font-size:12px;">
      Generated by Interview Intelligence | Powered by AI
    </p>
  </div>
</body>
</html>
"""


async def send_report_email(
    to_email: str,
    candidate_name: str,
    report: dict,
    session_id: str
) -> tuple[bool, str]:
    return await asyncio.to_thread(
        _send_email_sync,
        to_email,
        candidate_name,
        report,
        session_id
    )


def _send_email_sync(
    to_email: str,
    candidate_name: str,
    report: dict,
    session_id: str
) -> tuple[bool, str]:
    try:
        # Debug logs
        print("SMTP_USER:", SMTP_USER)
        print("PASS LENGTH:", len(SMTP_PASSWORD))

        ai_scores = report.get("ai_scores", {})

        html = Template(EMAIL_TEMPLATE).render(
            session_id=session_id,
            candidate_name=candidate_name or "Candidate",
            overall_score=report.get("overall_score", "N/A"),
            scores=ai_scores.get("scores", {}),
            strengths=ai_scores.get("strengths", []),
            weaknesses=ai_scores.get("weaknesses", []),
            tips=ai_scores.get("improvement_tips", [])
        )

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Your Interview Analysis Report — {session_id[:8]}"
        msg["From"] = FROM_EMAIL or SMTP_USER
        msg["To"] = to_email
        msg.attach(MIMEText(html, "html"))

        # Mock mode if SMTP not configured
        if not SMTP_USER or not SMTP_PASSWORD:
            print(f"[MOCK EMAIL] Sending simulated email to {to_email}")
            return True, "Mock email sent (SMTP not configured)."

        # Gmail SSL
        if SMTP_PORT == 465:
            with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT, timeout=20) as server:
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.sendmail(msg["From"], to_email, msg.as_string())

        # Gmail TLS
        else:
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=20) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.sendmail(msg["From"], to_email, msg.as_string())

        return True, "Report successfully sent."

    except smtplib.SMTPAuthenticationError as e:
        print("[AUTH ERROR]", e)
        return False, "Authentication failed. Check Gmail App Password."

    except TimeoutError:
        return False, f"Connection timed out to {SMTP_HOST}:{SMTP_PORT}"

    except Exception as e:
        print("[GENERAL ERROR]", e)
        return False, f"Failed to send email: {str(e)}"